### ISSUE TITLE
More specific selector for images contained in captions.

### ISSUE THREAD

**Issue by mfields** [Automattic/_s#116]
We currently use the following code to ensure that images within captions stretch to fill their containers.

``` css
.wp-caption img {
    display: block;
    margin: 1.2% auto 0;
    max-width: 98%;
}
```

I think that the scope of the selector is a bit too wide because it can easily target images contained within the caption paragraph were are meant to be displayed inline. This generally happens with smilies. The following code will ignore smilies.

``` css
.wp-caption img[class*="wp-image-"] {
    display: block;
    margin: 1.2% auto 0;
    max-width: 98%;
}
```

What do you think?
