### ISSUE TITLE
Add .alignnone to list of captioned images that get bottom margin.

### ISSUE THREAD

**Issue by mfields** [Automattic/_s#121]
If the last element in the post content is a captioned image that has a class of `alignnone` and something is appended to `the_content` like sharing links in Jetpack. There will be no whitespace between them: https://f.cloud.github.com/assets/468369/7546/e2959e8c-441b-11e2-8938-0c2c573d651c.png

The following should fix this:

``` css
.wp-caption.aligncenter,
.wp-caption.alignleft,
.wp-caption.alignright,
.wp-caption.alignnone {
    margin-bottom: 1.5em;
}
```

What do you think?
