### ISSUE TITLE
Update screen-reader-text class CSS

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1211]
[WP Accessibility repo](https://github.com/wpaccessibility/a11ythemepatterns/blob/master/read-more-links/style.css) already have updated CSS for `screen-reader-text`. There is also trac ticket [40970](https://core.trac.wordpress.org/ticket/40970) for the same update. 

In short we are adding `clip-path` for newer browsers but still leaving the `clip` (which is deprecated) for older browsers. Also adding `margin: -1px` to hide it completely from sight.

Suggested CSS:

```css
.screen-reader-text {
	border: 0;
	clip: rect(1px, 1px, 1px, 1px);
	clip-path: inset(50%);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute !important;
	width: 1px;
	word-wrap: normal !important; /* Many screen reader and browser combinations announce broken words as they would appear visually. */
}
``` 

Suggested focus styles:

```css
.screen-reader-text:focus {
	background-color: #f1f1f1;
	border-radius: 3px;
	box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.6);
	clip: auto !important;
        clip-path: none;
	color: #21759b;
	display: block;
	font-size: 14px;
	font-size: 0.875rem;
	font-weight: bold;
	height: auto;
	left: 5px;
	line-height: normal;
	padding: 15px 23px 14px;
	text-decoration: none;
	top: 5px;
	width: auto;
	z-index: 100000; /* Above WP toolbar. */
}
```
