### ISSUE TITLE
White screen in Safari and mobile Safari

### ISSUE THREAD

**Issue by ip00** [Automattic/_s#212]
Hi, 

I have had an issue with safari and mobile safari on two recently built sites. You could only see blank white screen in it although in other browsers everything was working fine. 

It was ok after we removed CSS lines, for clearing:

``` css
/* Clearing */
.clear:before,
.clear:after,
[class*="content"]:before,
[class*="content"]:after,
[class*="site"]:before,
[class*="site"]:after {
    content: '';
    display: table;
}

.clear:after,
[class*="content"]:after,
[class*="site"]:after {
    clear: both;
}
```

I'm not sure why this is happening in Safari. Something with the way we built our theme?

Thanks
