### ISSUE TITLE
Add box-sizing property to prevent image caption borders from getting cut off

### ISSUE THREAD

**Issue by designsimply** [Automattic/_s#341]
Add the box-sizing property to prevent image caption borders from getting cut off in responsive designs.

Example: https://cloudup.com/cQbJhGHywfW

``` css
.wp-caption {
-moz-box-sizing: border-box;
-webkit-box-sizing: border-box;
box-sizing: border-box;
}
```
