### ISSUE TITLE
function _s_posted_on() doesn't shows author name on front page

### ISSUE THREAD

**Issue by jaschaio** [Automattic/_s#705]
Hi,
the function `_s_posted_on()` inside `template-tags.php` just shows the author tag if the post is single, but not on the index.php

Its because in the stylesheet on line 742 it includes `.byline`

    .byline,
    .updated:not(.published) {
	display: none;
    }

Is this an intended behaviour?

**Comment by philiparthurmoore** [comment]
Yep, this is intended behavior. Bylines in index views will only be shown on multi-author blogs.

See this:

```css
.single .byline,
.group-blog .byline {
	display: inline;
}
```

Hope that helps!
