### ISSUE TITLE
Add a word-wrap to .comment-content

### ISSUE THREAD

**Issue by Paul-Browne** [Automattic/_s#96]
I always add 

``` css
.comment-content {
    word-wrap: break-word;
}
```

to my _s themes, as a prevention against someone who adds a really long url in a comment and screws up the layout, since it would just overflow out the box and result in an ugly x-scrollbar

just a thought
